use_frameworks!

target 'RxPaginator_Example' do
  pod 'RxPaginator', :path => '../'

  target 'RxPaginator_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
